import java.util.Arrays;

import soot.*;
import soot.options.Options;

public class Main1 {
	static boolean analyzeLibraries = false;
	static boolean useCHAForUnknown = false;
	static boolean useInline = true;

	public static void main(String[] args) {
		/*
		 * Ensure dacapo-9.12-MR1-bach.jar and out-* directories (classes and refl.log
		 * generated by TamiFlex)
		 * are in the current directory
		 */

		// Initialize Soot arguments

		GetSootArgs g = new GetSootArgs();

		if (args.length > 1) {
			if (args[1].equals("--analyze-libraries") || args[1].equals("-lib")) {
				analyzeLibraries = true;
			} else if (args[1].equals("-cha")) {
				useCHAForUnknown = true;
			} else if (args[1].equals("-no_inline")) {
				useInline = false;
			}
		}
		if (args.length > 2) {
			if (args[2].equals("-cha")) {
				useCHAForUnknown = true;
			} else if (args[2].equals("--analyze-libraries") || args[2].equals("-lib")) {
				analyzeLibraries = true;
			} else if (args[2].equals("-no_inline")) {
				useInline = false;
			}
		}

		if (args.length > 3) {
			if (args[3].equals("-no_inline")) {
				useInline = false;
			} else if (args[3].equals("--analyze-libraries") || args[2].equals("-lib")) {
				analyzeLibraries = true;
			} else if (args[3].equals("-cha")) {
				useCHAForUnknown = true;
			}
		}

		String[] sootArgs = g.getDaCapoArgs(args[0]);
		if (sootArgs == null) {
			System.out.println("Unable to generate args for soot!");
			return;
		}

		// Inter-procedural static analysis
		// SampleSceneTransform ipa = new SampleSceneTransform();
		ObjSensAnalysisTransformer analysisTransformer = new ObjSensAnalysisTransformer();
		PackManager.v().getPack("wjtp").add(new Transform("wjtp.ipa", analysisTransformer));

		// Options.v().set_exclude(Arrays.asList(
		// "sun.*",
		// "jdk.*"
		// ));
		Options.v().set_exclude(Arrays.asList(
				"sun.*"));
		Options.v().parse(sootArgs);
		Scene.v().loadNecessaryClasses();
		Scene.v().loadDynamicClasses();
		PackManager.v().runPacks();
	}
}